import React from "react";
import Link from "next/link";
import Head from "next/head";
import Header from "../components/Common/Header";
import Footer from "../components/Common/Footer";

interface LayoutProps {
  children: React.ReactNode;
}

const GenericLayout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Creader | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="w-3/4 mx-auto">{children}</main>
      <Footer />
    </>
  );
};

export default GenericLayout;
