// pages/about.tsx

import React from "react";
import Head from "next/head";

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>About Us - Decentralized Publishing Platform</title>
        <meta
          name="description"
          content="Learn more about our decentralized publishing platform and our mission to revolutionize the publishing industry."
        />
      </Head>

      <div className="container mx-auto mt-8">
        <h1 className="text-2xl font-bold mb-4">About Us</h1>
        <p className="mb-4">
          Our decentralized publishing platform is dedicated to providing
          authors and readers with a fair and transparent way to publish and
          access content. Our mission is to revolutionize the publishing
          industry by empowering authors to retain control over their works and
          enabling readers to support their favorite creators directly.
        </p>
        <p className="mb-4">
          By leveraging blockchain technology, we ensure that authors receive a
          fair share of the revenue generated by their works and that readers
          can access quality content without middlemen or restrictive DRM
          measures. Our platform fosters a thriving ecosystem where creativity
          and collaboration are encouraged, and everyone can benefit from the
          value they bring to the community.
        </p>
        <p>
          Join us in our journey to change the face of the publishing industry
          and help create a more equitable and open world for authors and
          readers alike.
        </p>
      </div>
    </>
  );
};

export default AboutUs;
