import Head from "next/head";
import Link from "next/link";
import ConnectButton from "@/app/components/ConnectButton";
import NextLink from "next/link";
import { Carousel } from "react-responsive-carousel";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faFacebook,
  faTwitter,
  faInstagram,
} from "@fortawesome/free-brands-svg-icons";

// import the facebook icon

export default function Home() {
  return (
    <>
      <Head>
        <title>Creader | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-blue-500 py-4">
        <nav className="container mx-auto flex justify-between items-center">
          <h1 className="text-white font-bold text-xl">
            Decentralized Publishing
          </h1>
          <ul className="flex space-x-4">
            <li>
              <NextLink className="text-white" href="/author-dashboard">
                Dashboard
              </NextLink>
            </li>
            <li>
              <NextLink className="text-white" href="/profile">
                Profile
              </NextLink>
            </li>
            <li>
              <NextLink className="text-white" href="/logout">
                Log Out
              </NextLink>
            </li>
          </ul>
        </nav>
      </header>
      <div className="bg-gradient-to-r from-blue-500 to-green-500 text-white py-20 text-center">
        <h1 className="text-4xl font-bold mb-4">Welcome to Creader</h1>
        <p className="text-xl mb-4">
          A decentralized platform for publishing and protecting your literary
          works
        </p>
        <ConnectButton></ConnectButton>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 py-16 px-8">
        <div className="bg-gray-100 p-8 rounded">
          <h2 className="text-2xl font-bold mb-4">For Authors</h2>
          <p>
            Create, manage, and protect your literary works using blockchain
            technology. Get rewarded for your creative efforts and maintain full
            control over your work.
          </p>
        </div>
        <div className="bg-gray-100 p-8 rounded">
          <h2 className="text-2xl font-bold mb-4">For Readers</h2>
          <p>
            Discover unique and engaging content created by talented authors.
            Support your favorite creators and enjoy a seamless reading
            experience on our platform.
          </p>
        </div>
      </div>
      {/* Feature Highlights */}
      <div className="py-16 px-8">
        <h2 className="text-3xl font-bold mb-8 text-center">
          Platform Features
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="bg-blue-500 text-white p-6 rounded mb-4">Icon</div>
            <h3 className="text-xl font-bold mb-2">Copyright Protection</h3>
            <p>
              Secure your work with blockchain-based copyright protection and
              NFTs.
            </p>
          </div>
          <div className="text-center">
            <div className="bg-blue-500 text-white p-6 rounded mb-4">Icon</div>
            <h3 className="text-xl font-bold mb-2">Revenue Sharing</h3>
            <p>
              Earn a fair share of revenue from your work through our token
              system.
            </p>
          </div>
          <div className="text-center">
            <div className="bg-blue-500 text-white p-6 rounded mb-4">Icon</div>
            <h3 className="text-xl font-bold mb-2">Community Engagement</h3>
            <p>
              Connect with readers and other authors in a decentralized
              community.
            </p>
          </div>
        </div>
      </div>
      {/* Testimonials */}
      <div className="bg-gray-100 py-16 px-8">
        <h2 className="text-3xl font-bold mb-8 text-center">
          What Our Users Say
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="p-8 bg-white rounded">
            <p className="italic mb-4">
              "Creader has revolutionized the way I publish and protect my work.
              I have full control over my content and receive fair
              compensation."
            </p>
            <p className="font-bold">- Author Name</p>
          </div>
          <div className="p-8 bg-white rounded">
            <p className="italic mb-4">
              "I love discovering new authors and supporting their work on
              Creader. The platform offers a great reading experience and a
              strong sense of community."
            </p>
            <p className="font-bold">- Reader Name</p>
          </div>
        </div>
      </div>

      {/* Popular Works */}
      <div className="py-16 px-8">
        <h2 className="text-3xl font-bold mb-8 text-center">Popular Works</h2>
        <Carousel
          showThumbs={false}
          showStatus={false}
          showArrows={true}
          showIndicators={false}
          infiniteLoop={true}
          autoPlay={true}
          interval={5000}
          stopOnHover={true}
          swipeable={true}
          dynamicHeight={false}
          emulateTouch={false}
        >
          {/* Replace with actual popular works data */}
          {Array.from({ length: 6 }).map((_, i) => (
            <figure
              className="p-4 bg-gray-100 rounded shadow flex flex-col md:flex-row text-center"
              key={i}
            >
              <div className="bg-gray-300 rounded-none w-full md:w-1/2 h-40 md:h-auto mb-4 md:mb-0">
                ss
              </div>
              <div className="md:ml-4 text-center md:text-left space-y-2 flex-1">
                <h3 className="text-xl font-bold mb-2">Book Title {i + 1}</h3>
                <p className="text-sm">Rating: 4.5/5</p>
                <p className="m-0 text-slate-700 dark:text-slate-500">
                  Fiction
                </p>
                <blockquote>
                  <p className="text-lg font-medium">
                    Short description of the book goes here. This is just a
                    placeholder text.
                  </p>
                </blockquote>
                <figcaption className="font-medium">
                  <div className="text-sky-500 dark:text-sky-400">
                    Sarah Dayan
                  </div>
                </figcaption>
                <button className="bg-blue-500 text-white font-bold py-2 px-4 rounded">
                  <NextLink href="/bookdetail">View Work</NextLink>
                </button>
              </div>
            </figure>
          ))}
        </Carousel>
      </div>

      <div className="text-center py-16">
        <h2 className="text-3xl font-bold mb-8">Get Started Today</h2>
        <button className="bg-blue-500 text-white px-6 py-3 rounded">
          Sign Up
        </button>
      </div>

      {/* Footer */}
      <footer className="bg-blue-500 text-white py-12">
        <div className="container mx-auto px-4">
          <div className="flex flex-wrap justify-between mb-8">
            <div className="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 mb-8">
              <h3 className="text-xl font-bold mb-4">Platform</h3>
              <ul>
                <li className="mb-2">
                  <a href="#" className="text-sm hover:text-gray-300">
                    Home
                  </a>
                </li>
                <li className="mb-2">
                  <a href="#" className="text-sm hover:text-gray-300">
                    About Us
                  </a>
                </li>
                <li className="mb-2">
                  <a href="#" className="text-sm hover:text-gray-300">
                    Contact Us
                  </a>
                </li>
              </ul>
            </div>

            <div className="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 mb-8">
              <h3 className="text-xl font-bold mb-4">Community</h3>
              <ul>
                <li className="mb-2">
                  <a href="#" className="text-sm hover:text-gray-300">
                    Blog
                  </a>
                </li>
                <li className="mb-2">
                  <a href="#" className="text-sm hover:text-gray-300">
                    Forum
                  </a>
                </li>
                <li className="mb-2">
                  <a href="#" className="text-sm hover:text-gray-300">
                    Support
                  </a>
                </li>
              </ul>
            </div>

            <div className="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 mb-8">
              <h3 className="text-xl font-bold mb-4">Legal</h3>
              <ul>
                <li className="mb-2">
                  <a href="#" className="text-sm hover:text-gray-300">
                    Terms of Service
                  </a>
                </li>
                <li className="mb-2">
                  <a href="#" className="text-sm hover:text-gray-300">
                    Privacy Policy
                  </a>
                </li>
                <li className="mb-2">
                  <a href="#" className="text-sm hover:text-gray-300">
                    Cookie Policy
                  </a>
                </li>
              </ul>
            </div>

            <div className="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 mb-8">
              <h3 className="text-xl font-bold mb-4">Connect</h3>
              <p className="mb-4">Follow us on social media:</p>
              <div className="flex space-x-4">
                <a href="#" className="text-xl hover:text-gray-300">
                  <FontAwesomeIcon
                    icon={faFacebook}
                    style={{ fontSize: 20, color: "white" }}
                  />
                </a>
                <a href="#" className="text-xl hover:text-gray-300">
                  <FontAwesomeIcon
                    icon={faInstagram}
                    style={{ fontSize: 20, color: "white" }}
                  />
                </a>
                <a href="#" className="text-xl hover:text-gray-300">
                  <FontAwesomeIcon
                    icon={faTwitter}
                    style={{ fontSize: 20, color: "white" }}
                  />
                </a>
              </div>
            </div>
          </div>

          <div className="border-t border-gray-700 pt-4 text-center">
            <p className="text-sm">
              © {new Date().getFullYear()} Creader.io All rights reserved.
            </p>
          </div>
        </section>
      </main>
      <footer className="bg-blue-500 py-4 text-center text-white">
        <p>&copy; Creader.io 2023</p>
      </footer>
    </>
  );
}
